<?xml version="1.0" encoding="iso-8859-15"?>
<!DOCTYPE documentos [

<!ELEMENT documentos (libros,revistas,periodicos)>
<!-- empieza libros-->
<!ELEMENT libros (libro)>
    <!ELEMENT libro (titulo, capitulo, indice, sinopsis)>
        <!ATTLIST libro tipo_clase (novela|infantil|didactico|teoria_cineomatografica) "novela">
        <!ATTLIST libro id_libro ID #REQUIRED>
        <!ATTLIST libro npag NMTOKEN >
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT capitulos (contenido, titulo_capitulo)>
        <!ELEMENT titulo_capitulo (#PCDATA)>
        <!ATTLIST titulo_capitulo npag NMTOKEN>
        <!ELEMENT contenido (#PCDATA)>
    <!ELEMENT indice (#PCDATA)>
    <!ELEMENT sinopsis (#PCDATA)>
<!-- empieza revistas-->
<!ELEMENT revistas (revista)>
    <!ELEMENT revista (titulo, nrevista, indice, seccion)>
        <!ATTLIST revista tipo_clase (informatica|corazon|coches|investigacion|psicologia) "informatica">
        <!ATTLIST revista npag NMTOKEN>
        <!ATTLIST revita id_revista ID #REQUIRED>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT nrevista (#PCDATA)>
    <!ELEMENT indice (#PCDATA)>
    <!ELEMENT secciones (contenido)>
        <!ATTLIST secciones npagseccion NMTOKEN>
        <!ELEMENT contenido (#PCDATA)>
<!-- empieza periodicos-->
<!ELEMENT periodicos (periodico)>
    <!ELEMENT periodico (secciones, indice)
        <!ATTLIST periodicos tipo_clase (nacional|internacional) "nacional">
        <!ATTLIST periodicos fecha_salida CDATA>
        <!ATTLIST periodicos id_periodicos ID #REQUIRED>
    <!ELEMENT indice (#PCDATA)>
    <!ELEMENT secciones (articulos)>
        <!ATTLIST secciones tipo_seccion (economica|opinion|deportes|nacional|internacionas) "economica">
    <!ELEMENT articulos (#PCDATA)>
        <!ATTLIST articulos autor CDATA>
]>

<documentos>
    <libros>
        <libro tipo_clase="teoria_cineomatografica" id_libro="L1234" npag="267">
            <titulo>Esculpir en el tiempo</titulo>
            <indice>
                        INDICE
                Prólogo             7
                Presentación        11
                introducción        21
                Los Comienzos       31
            </indice>
            <capitulos>
                <titulo_capitulo npag="18">El arte como ansia de lo ideal</titulo_capitulo>
                <contenido>
                    el objetivo de cualquier arte que no quiera ser consumido como una
                    mercancia consiste en explicar a si mismo y a su entrono el sentido
                    de la viday de la existencia humana
                </contenido>
            </capitulos>
            <sinopsis>
                Con ayuda del cine se pueden tratar las cuestiones más complejas del 
                presente a un nivel que durante siglos ha sido propio de la literatura,
                la música o la pintura.               
            </sinopsis>
        </libro>
    </libros>
    <revistas>
        <revista tipo_clase="psicologia" id_revista="R" npag="30">
            <titulo>Presionados por el tiempo</titulo>
            <nrevista>15</nrevista>
            <indice>
                        INDICE
                En sintesis                     1
                Una cuestion de perspectiva     15
            </indice>
            <secciones npagseccion="15">
                <contenido>
                    Las razones de este fenómeno son diversas.
                    La interconexión de los procesos económicos, la masa de información y bienes,
                    la comunicación permanente, todo ello contribuye a que la vida laboral actual
                    sea más compleja, rápida y exigente de lo que era hace unos años.
                </contenido>
            </secciones>
        </revista>
    </revistas>
    <periodicos>
        <periodico id_periodicos="P1520" tipo_clase="internacional" fecha_salida="18/05/2021">
            <indice>Noticia unica</indice>
            <secciones tipo_seccion="economica">
                <articulos autor="anonimo">Despidos masivos de trabajadores del metro de Moscú simpatizantes de Navalni</articulos>
            </secciones>
        </periodico>
    </periodicos>
</documentos>
